.gitignore, src/main/resources/logback.xml
Because of a requirement of the ops team we need an explicit log file. So I've added a FileAppender to our logback config which will write all messages in the same format as to the console in the file efgs.log
=> *feat: Log in seperate file

src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java, src/test/java/eu/interop/federationgateway/TestData.java, src/test/java/eu/interop/federationgateway/batchsigning/SignatureGenerator.java
We got an "X.509 not found" error on dev environment. Removing of the ```addProvider()``` method fixes this behaviour.
=> Removed setup of BouncyCastly provider

src/main/java/eu/interop/federationgateway/controller/CallbackAdminController.java, src/test/java/eu/interop/federationgateway/controller/CallbackAdminControllerTest.java
To comply with architecture documentation I have changed the url parameter of the callback admin endpoint from header to query parameter.
=> *fix: URL parameter for callback admin is not a query param

src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java, src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java
Ops asked us to implement URL encoding to both authentication headers.
=> *feat: URL encoding for cert-thumbprint and dn-string headers

src/main/java/eu/interop/federationgateway/config/ProtobufHttpMessageConverter.java, src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java, src/main/java/eu/interop/federationgateway/service/CallbackService.java, src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java, src/main/java/eu/interop/federationgateway/service/CertificateService.java, src/main/java/eu/interop/federationgateway/service/DiagnosisKeyBatchService.java
Added parentesis to MDC logging parameters to not break log format.
=> *fix: surrounded complex MDC parameters with parentesis

src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidator.java
see https://developers.google.com/android/exposure-notifications/exposure-key-file-format 
closes #129
=> Fix: Input-Validator accepts a rolling-start-interval with value 0 

.github/workflows/ci-master.yml
This should make setting up testing environment easier without installing Java and building images.
Fixes #89
=> Publish latest docker image in GitHub Docker registry

src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java, src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java, src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java
Changed behaviour of upload to return ids of possibly inserted keys on failure.
This fixes #135
=> fix: Return number of possibly inserted keys on upload failure.

src/test/java/eu/interop/federationgateway/batchsigning/SignatureGenerator.java
When calling `addSignerInfoGenerator` method, a parameter named
`signerInfoMustBeAdded` should be checked, not `certMustBeAdded`.
The same goes for `addCertificate` method, `certMustBeAdded`
parameter should be checked before calling it.
=> Swap conditions according to methods called inside

pom.xml
There's no plugin version for 'maven-surefire-plugin´ so Maven shows a warning:
[WARNING] Some problems were encountered while building the effective model for eu.interop.federationgateway:efgs-federation-gateway:jar:1.0.0-RC5
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 340, column 15
I also set up pluginManagement for other plugins.
=> fix: Maven plugin 'maven-surefire-plugin' warning

src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureUtils.java
Diagnosiskey batches were converted twice. With this patch they are converted, sorted and then put into the ByteStream.
=> Fix: Optimized Sorting of Diagnosis Keys

pom.xml
Naming convention is with hyphen (-) not point (.). 
It should be 1.0.1.-SNAPSHOT; not 1.0.1.SNAPSHOT.
=> Naming convention for SNAPSHOT versions

src/main/java/eu/interop/federationgateway/mapper/DiagnosisKeyMapper.java, src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
The loop in `saveDiagnosisKeyEntities` is currently O(n^2) complexity because the delegated lambda is immediately calling indexOf on the key.
Proposed
* use standard for loop and get(i)
* ensure that the list is of ArrayList type (it already likely was by default, but Collectors.toList does not force an implementation).
=> runtime improvements

src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java, src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java
DN-String parser allows duplicated keys
=> fix: Auth-Certificate subject cannot contain duplicated keys

pom.xml, src/main/java/eu/interop/federationgateway/mapper/DiagnosisKeyMapper.java, src/test/java/eu/interop/federationgateway/mapper/DiagnosiskeyMapperTest.java
When downloading keys the visited countries array contains an ""-String when no visited countries were submitted to EFGS. It is expected that EFGS returns an empty array.
=> fix: visited countries array contains empty string if visited countries is empty

src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java, src/main/java/eu/interop/federationgateway/service/TransactionalCallbackTaskExecutorService.java, src/test/java/eu/interop/federationgateway/service/CallbackTaskExecutorServiceTest.java
This PR adresses tickets #248  and #247 
The handling of requests in CallbackTaskExecutor is switched from .exchange to .retrieve. Also the transactional methods are now in a seperate class so that the @Transactional annotation has a real effect.
=> Callback: Request handling and transactional

src/main/resources/db/changelog.yml, src/main/resources/db/changelog/v001-change-certificate-signature-column-size.yml, src/test/java/eu/interop/federationgateway/TestData.java
Increased size of certificate signature column to support trust anchors with private key with up to 4096 bit key size.
closes #217
=> fix: TrustAnchor up to 4096 bit key size

src/main/java/eu/interop/federationgateway/service/CallbackTaskCleanupService.java, src/main/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupService.java, src/main/resources/application.yml, src/test/resources/application.yml
Added a Shedlock config for DiagnosisKeyCleanupJob and CallbackTaskCleanupJob to prevent missleading error messages.
This PR closes #234
=> Shedlock for DiagnosisKeyCleanup and CallbackTaskCleanup

docs/openapi.json, src/main/java/eu/interop/federationgateway/controller/UploadController.java
Updated documents for more clearness on how to name batchtags.
The batchtags must be unique systemwide. A common proceed to achieve this would be to prefix or attach a hash value or the country initials.
=> fix: document-unique-upload-batchtag

tools/create_callback_client_certificate.sh, tools/create_certificate_signature.bat, tools/create_certificate_signature.sh, tools/create_trustanchor.bat, tools/create_trustanchor.sh
This PR fixes #242 and #244 and improves the bash scripts to fail on error.
=> Fix: Make tools run on Linux and macos 

src/main/resources/db/changelog/v000-create-callback-subscription-entity-table.yml, src/main/resources/db/changelog/v000-create-callback-task-entity-table.yml, src/main/resources/db/changelog/v000-create-certificate-entity-table.yml
The explicit auto increment changeset is not needed as long as we have a
```
autoincrement: true
```
constraint on the id fields.
Deleting the whole changeset does not affect existing databases, so it is safe to remove it.
=> fix: Removed unnecessary auto increment changesets

pom.xml, src/main/docker/docker-compose.override.yml, src/main/docker/docker-compose.psql.yml, src/main/docker/docker-compose.yml, src/main/resources/application-psql.yml, src/main/resources/db/changelog/v000-create-callback-subscription-entity-table.yml, src/main/resources/db/changelog/v000-create-callback-task-entity-table.yml, src/main/resources/db/changelog/v000-create-certificate-entity-table.yml
Since the EFGS does not officially support postgres, we split https://github.com/eu-federation-gateway-service/efgs-federation-gateway/pull/257 into a `database-agnostic` [fix](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/pull/258), which removed the duplication of `autoIncrement`, and this PR, a  postgres specific one.
In this PR we add the postgres connector to the `POM.xml`, splitted the `docker-compose.yml` to allow the use of shared docker files and added a basic example `application-psql.yml`, which exposes the `psql` profile to spring.
In order to build and run the `docker-compose` with postgres use `docker-compose -f docker-compose.yml -f docker-compose.psql.yml up --build`.
=> Add Postgres Example to community branch

pom.xml
Updated dependencies:
Spring Boot: 2.4.1 --> 2.4.3
Spring Cloud: 2020.0.0 --> 2020.0.1
Spring Security: 5.4.2 --> 5.4.5
Lombok: 1.18.16 --> 1.18.18
Liquibase: 4.2.2 --> 4.3.1
SpringDoc: 1.5.2 --> 1.5.4
Mapstruct: 14.1.Final --> 1.4.2.Final
okhttp: 4.9.0 --> 4.9.1
Test
JUnit: 5.7.0 --> 5.7.1
Mockito: 3.7.0 --> 3.7.7
Spring Test: 5.3.2 --> 5.3.4
Plugins
owasp: 6.0.5 --> 6.1.1
checkstyle: 3.1.1 --> 3.1.2
OS-Maven: 1.6.2 --> 1.7.0
=> Dependency Update Spring Boot 2.4.3

src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java, src/main/java/eu/interop/federationgateway/service/TransactionalCallbackTaskExecutorService.java
The transaction handling of callback handling was not optimal.
The "Not-Before"-constraint removal and the deletion of current task was in two transactions. This makes no sense. So now these to steps are merged into one transaction.
=> Little Improvement of Transaction Handling

src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyBatchRepository.java, src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java, src/main/resources/application.yml
**Memory Optimization**: Deleting Diagnosis keys always resulted in loading alle keys to be deleted into heap. This can cause a OutOfMemoryException.
To avoid this the deleting of DiagnosisKeys and DiagnosisKeyBatches has been changed to direct querys.
**Thread Pool Scheduled Jobs**: Springs default ThreadPool-Size for scheduled jobs is 1. As long as EFGS has some background jobs which are executed regulary we increased the ThreadPool-Size for better load balancing.
This could have a positive effect for #262
=> fix: Memory Optimization and ThreadPool for Scheduled Jobs

tools/create_certificate_signature.bat
With 1.0.6 a improved version of create_certificate_signature.bat was released. But the 
```
SET /P CERT_BASE64=<cert.base64
```
is limited to a maximum of 1024 characters. All base64 strings of certificate raw data have much more chars.
In order to recover functionality this change has been rolled back.
closes #263
=> Reverted change in batch script regarding certificate raw data handling

pom.xml
Currently the OWASP Check Job fails. The update to Spring Boot 2.4.5 includes an updated peer dependency which raised the failed OWASP check.
=> Update Spring Boot to 2.4.5

src/main/resources/application.yml
Set the property for max age to 2 days. This ensures that no key exists longer than 72h in EFGS database.
=> Set Key Retention to 3 Days

src/main/resources/db/changelog.yml, src/main/resources/db/changelog/v003-increase-column-size-for-batchsignature.yml
Closes: https://github.com/eu-federation-gateway-service/efgs-federation-gateway/issues/276
We increase the column size to 8000 characters, to circumvent the issues of longer RSA keys in the certificates used for signing the uploaded batches. See the linked issue for further details.
=> Add Migration to Increase `uploader_information_batch_signature` Column Size

src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java, src/test/java/eu/interop/federationgateway/service/CallbackTaskExecutorServiceTest.java
Added fixed UserAgent for outbound Callback Requests to mitigate risk of exposure of internal values.
=> Add fixed UserAgent to Callback Requests

docs/software-design-federation-gateway-service.md, src/main/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupService.java
When the Cleanup Job failes it will be tried again after 10 minutes. This PR should mitigate failing cleanup when EFGS has high database load.
=> Add Retry Logic for Cleanup Job

src/main/java/eu/interop/federationgateway/config/EfgsProperties.java
This PR adds a temporary workaround to enable loading the DB encryption password from System Property (as it was in <= 1.0.7)
=> Workaround for DB Encryption password

owasp/suppressions.xml, pom.xml, src/main/resources/db/changelog/v000-create-diagnosis-key-batch-entity-table.yml
The Liquibase Changeset ```v000-create-diagnosis-key-batch-entity-table.yml``` contains an ```incrementBy``` property which is not supported by MySql. It's not required for our database schema.
=> Fix: Liquibase Changelog when starting on blank MySql
