eu-federation-gateway-service/efgs-federation-gateway

pom.xml

The ops teams asked for endpoints to monitor this application.

*feat: Enabled SpringBoot-Actuator

---

README.md
pom.xml
src/main/docker/Dockerfile
src/main/docker/db/01-init.sql
src/main/docker/docker-compose.yml
src/main/resources/application-dev.yml
src/main/resources/application-h2.yml
src/main/resources/application-mysql.yml
src/main/resources/application.yml
src/test/resources/application.yml

Based on PR #35 I've implemented a tradeoff between development teams requirements and @iCesofTs proposal for docker integration.
Also this implementation respects the latest changes regarding JNDI support.

*feat: Docker support for local testing, Spring update, profile restructuring

---

src/main/resources/db/changelog/v000-create-diagnosis-key-entity-table.yml

Increased possible batch signature size to allow certificates with more information for batch signing.

*feat: Higher Batch Signature Size

---

src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java

*fix: Full Group By Error for AuditLog fixed

---

src/main/docker/docker-compose.yml

Bumped MySQL Version in Docker-Compose file to 5.7

*feat: Support for MySQL 5.7

---

src/main/java/eu/interop/federationgateway/config/ErrorHandler.java

Extended Error handler to catch all exceptions and present them as JSON format.
Forced JSON format for ResponseStatusExceptions.

*feat: Error Handling for all Exceptions

---

docs/software-design-federation-gateway-service.md
src/main/resources/logback.xml

Implemented Log-Rotation
Added relative path for tomcat env

*feat: Log-Rotation

---

README.md

Added a hint in readme file how to build project with activated docker profile.
this PR closes #47

Added maven profile hint to readme

---

docs/software-design-federation-gateway-service.md

Put some of the things dicussed in the last telecon in, add some addtional suggestions/refinements.

Small suggestions.

---

src/main/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupService.java

Fixed Cron Expression for Data retention job (added seconds to comply Spring Cron Format)

*fix: Cron Expression for Retention Job

---

docs/software-design-federation-gateway-service.md

Added detail information about hash format for request forwarding.

*fix: Added details for cert hashing

---

README.md

Fix Swagger UI link documentation

---

src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java
src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java

Replaced URL decoding with Base64 decoding for cert hash header.

*feat:  Base64 decoding of Certificate-Hash header

---

docs/software-design-federation-gateway-service.md

Updated documentation for load balancer request headers.

doc: Updated Load Balancer header

---

src/main/java/eu/interop/federationgateway/config/ErrorHandler.java
src/main/java/eu/interop/federationgateway/controller/UploadController.java
src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchConstraint.java
src/main/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidator.java
src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java
src/test/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidatorTest.java

Feat: Input-Validator for DiagnosisKeys

---

docs/software-design-federation-gateway-service.md

Update links to architecture document

---

docs/software-design-federation-gateway-service.md
src/main/docker/Dockerfile
src/main/docker/db/01-init.sql
src/main/docker/docker-compose.yml
src/main/java/eu/interop/federationgateway/config/EfgsPropertiesValidator.java
src/main/java/eu/interop/federationgateway/controller/DownloadController.java
src/main/java/eu/interop/federationgateway/entity/FormatInformation.java
src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyBatchRepository.java
src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
src/main/java/eu/interop/federationgateway/service/DiagnosisKeyBatchService.java
src/main/resources/application.yml
src/test/java/eu/interop/federationgateway/TestData.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyBatchServiceTest.java

To fix this issue the batching process needed a refactoring.
Now it is much faster and can handle uploads during it is executed.
This PR closes #73 and closes #15

fix: Upload Timeouts When Batching

---

src/main/java/eu/interop/federationgateway/controller/AuditController.java
src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java

Feat: Audit-download will be requested with date and batchtag

---

src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java

Removed Certificate Signature Verification from BatchVerifier
#fixes #94

fix: Ca signed signing certificates are not working

---

docs/openapi.json

Fix: update openapi.json 

---

src/main/java/eu/interop/federationgateway/repository/CallbackTaskRepository.java
src/main/java/eu/interop/federationgateway/service/CallbackTaskExecutorService.java
src/test/java/eu/interop/federationgateway/service/CallbackTaskExecutorServiceTest.java

Fixed failure of callback executor when multiple callback tasks are pending.

fix: Callback Exception when more then one callback is pending

---

docs/openapi.json
docs/software-design-federation-gateway-service.md
src/main/java/eu/interop/federationgateway/controller/DiagnosisKeyController.java
src/main/java/eu/interop/federationgateway/controller/DownloadController.java
src/main/java/eu/interop/federationgateway/controller/UploadController.java
src/test/java/eu/interop/federationgateway/controller/DiagnosisKeyControllerTest.java
src/test/java/eu/interop/federationgateway/controller/DownloadControllerTest.java
src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java

fix: Extract options-endpoint from upload and download to [OPTIONS] /diagnosiskeys

---

src/main/java/eu/interop/federationgateway/service/CallbackService.java

Updated to avoid duplicate attributes in logs

---

src/main/java/eu/interop/federationgateway/config/EfgsProperties.java
src/main/java/eu/interop/federationgateway/config/EfgsPropertiesValidator.java
src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionByteArrayConverter.java
src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionIntConverter.java
src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionReportTypeConverter.java
src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionService.java
src/main/java/eu/interop/federationgateway/dbencryption/DbEncryptionStringConverter.java
src/main/java/eu/interop/federationgateway/entity/DiagnosisKeyPayload.java
src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
src/main/resources/application-dev.yml
src/main/resources/application.yml
src/main/resources/db/changelog.yml
src/main/resources/db/changelog/v001-update-diagnosiskeypayload_encryption.yml
src/test/java/eu/interop/federationgateway/dbencryption/DbEncryptionTest.java
src/test/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepositoryTest.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java
src/test/resources/application.yml

- Removed unused findDiagnosisKeyByVisitedCountry method
- Implemented AES-256 data encryption for in database stored DiagnosisKeyPayload
- Added DB changelog to alter diagnosis key payload columns to be able to hold encrypted strings
- Added Validator for DB Encryption properties
closes #113

feat: DiagnosisKey encryption in database

---

docs/openapi.json
src/main/java/eu/interop/federationgateway/controller/AuditController.java
src/main/java/eu/interop/federationgateway/controller/DownloadController.java

fix: Update Http 400 Status openApi.json for Download and Audit

---

docs/software-design-federation-gateway-service.md
src/main/java/eu/interop/federationgateway/service/CertificateService.java

Added certificate verification log messages to documentation.
closes #122

feat: Log message documentation for cert integrity check

---

src/main/resources/application-dev.yml
src/main/resources/application.yml

feat: Disable Swagger Endpoint for PRD

---

src/main/java/eu/interop/federationgateway/FederationGatewayApplication.java
src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureUtils.java
src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java
src/main/java/eu/interop/federationgateway/config/EfgsKeyStore.java
src/main/java/eu/interop/federationgateway/config/ProtobufHttpMessageConverter.java
src/main/java/eu/interop/federationgateway/controller/DownloadController.java
src/main/java/eu/interop/federationgateway/entity/CallbackSubscriptionEntity.java
src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java
src/main/java/eu/interop/federationgateway/service/DiagnosisKeyBatchService.java
src/main/java/eu/interop/federationgateway/service/TransactionalDiagnosisKeyBatchService.java
src/main/java/eu/interop/federationgateway/utils/CertificateUtils.java
src/main/java/eu/interop/federationgateway/utils/EfgsMdc.java
src/main/java/eu/interop/federationgateway/utils/SemVerUtils.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyBatchServiceTest.java

fixed several sonarcube bugs

---

src/main/resources/application-dev.yml
src/main/resources/application.yml

Disabled Swagger for prod

---

.github/workflows/ci-master.yml
src/main/java/eu/interop/federationgateway/config/EfgsKeyStore.java

Change try to try with ressource

fix: Change try to try with ressource 

---

.gitignore
NOTICE
README.md
src/main/docker/docker-compose.yml
tools/create_callback_client_certificate.bat
tools/create_callback_client_certificate.sh
tools/create_certificate_signature.bat
tools/create_certificate_signature.sh
tools/create_trustanchor.bat
tools/create_trustanchor.sh

Added documentation about creating certificates to README.md
Added scripts for certificate creation

Doc: Added documentation for Docker image & Added scripts for certificate creation

---

README.md

Consistency: adding to (previously unfilled) "Contributors" section in [`readme`](https://github.com/eu-federation-gateway-service/efgs-federation-gateway) (Cf. `NOTICE`) ).

Provided acknowledgment to the "Contributors" section of README.md.

---

owasp/suppressions.xml
pom.xml

Added OWASP Check to build chain.
Upgraded SpringDoc to remove Vulnerability.
closes #191

feat: OWASP Dependency Check for Build Chain

---

src/main/java/eu/interop/federationgateway/config/EfgsProperties.java
src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java

extend the time interval regarding the midnight upload and batch issue

fix: AuditEntry and midnight

---

src/main/java/eu/interop/federationgateway/filter/CertificateAuthentificationFilter.java
src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java

fix: Leading zero in cert thumbprint leads to error

---

src/main/java/eu/interop/federationgateway/service/TransactionalDiagnosisKeyBatchService.java

fixed dublicated BatchTag Name creation at midnight

fix: dublicated batch tag when batched at midnight

---

owasp/suppressions.xml
src/main/java/eu/interop/federationgateway/model/AuditEntry.java
src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepository.java
src/main/java/eu/interop/federationgateway/service/DiagnosisKeyEntityService.java
src/test/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepositoryTest.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java

fix: Audit Endpoint wrong order

---

pom.xml

chore:lift version 1.0.5

---

owasp/suppressions.xml
pom.xml
src/main/java/eu/interop/federationgateway/config/WebClientConfig.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

Updated dependencies to current versions.
* Updated Spring Boot to 2.4.1
* Updated to Junit 5 (Jupiter)
These changes fix our current OWASP findings

Updated dependencies (Spring Boot 2.4.1)

---

src/main/java/eu/interop/federationgateway/service/CertificateService.java
src/test/java/eu/interop/federationgateway/TestData.java
src/test/java/eu/interop/federationgateway/batchsigning/SignatureGenerator.java

Hardcoded SHA256with signature algorithm replaced with signature algorithm vom X509Certificate
closes #147

fix: Read Signature Algorithm for TrustAnchor

---

src/main/java/eu/interop/federationgateway/config/ProtobufConverter.java
src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java

An invalid base64 in JSON upload does not lead to a 500 status code anymore.
This PR closes #215

Added error handling for invalid base64

---

pom.xml

lift version for release 1.0.6

chore: release 1.0.6

---

src/main/java/eu/interop/federationgateway/config/MdcCleanupInterceptor.java
src/main/java/eu/interop/federationgateway/config/WebMvcConfig.java
src/main/java/eu/interop/federationgateway/controller/AuditController.java
src/main/java/eu/interop/federationgateway/controller/DownloadController.java
src/main/java/eu/interop/federationgateway/controller/UploadController.java

The MDC sometimes contains data from old requests. This PR adds an interceptor which will clean up the MDC after each request.

Cleanup MDC after each Request

---

src/main/java/eu/interop/federationgateway/controller/DownloadController.java
src/main/java/eu/interop/federationgateway/repository/DiagnosisKeyBatchRepository.java
src/main/java/eu/interop/federationgateway/service/DiagnosisKeyBatchService.java
src/main/java/eu/interop/federationgateway/service/TransactionalDiagnosisKeyBatchService.java
src/test/java/eu/interop/federationgateway/controller/DownloadControllerTest.java
src/test/java/eu/interop/federationgateway/repository/DiagnosisKeyBatchRepositoryTest.java

Add Support to DownloadKeys "Newer Than"

---

pom.xml
src/test/java/eu/interop/federationgateway/batchsigning/BatchSignatureUtilsTest.java
src/test/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifierTest.java
src/test/java/eu/interop/federationgateway/controller/AuditControllerTest.java
src/test/java/eu/interop/federationgateway/controller/CallbackAdminControllerTest.java
src/test/java/eu/interop/federationgateway/controller/DiagnosisKeyControllerTest.java
src/test/java/eu/interop/federationgateway/controller/DownloadControllerTest.java
src/test/java/eu/interop/federationgateway/controller/UploadControllerTest.java
src/test/java/eu/interop/federationgateway/dbencryption/DbEncryptionTest.java
src/test/java/eu/interop/federationgateway/filter/CertAuthFilterTest.java
src/test/java/eu/interop/federationgateway/mapper/DiagnosiskeyMapperTest.java
src/test/java/eu/interop/federationgateway/mtls/EfgsCallbackTrustManagerTest.java
src/test/java/eu/interop/federationgateway/repository/CallbackTaskRepositoryTest.java
src/test/java/eu/interop/federationgateway/repository/DiagnosisKeyBatchRepositoryTest.java
src/test/java/eu/interop/federationgateway/repository/DiagnosisKeyEntityRepositoryTest.java
src/test/java/eu/interop/federationgateway/service/CallbackServiceTest.java
src/test/java/eu/interop/federationgateway/service/CallbackTaskCleanupServiceTest.java
src/test/java/eu/interop/federationgateway/service/CallbackTaskExecutorServiceTest.java
src/test/java/eu/interop/federationgateway/service/CertificateServiceTest.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyBatchServiceTest.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyCleanupServiceTest.java
src/test/java/eu/interop/federationgateway/service/DiagnosisKeyEntityServiceTest.java
src/test/java/eu/interop/federationgateway/testdata/TestDataGenerator.java
src/test/java/eu/interop/federationgateway/utils/SemVerUtilsTest.java
src/test/java/eu/interop/federationgateway/validator/DiagnosisKeyBatchValidatorTest.java

Updated dependencies to most recent versions. This PR also includes a migration of the Unit Tests to JUnit5

Chore: Updated Dependencies

---

owasp/suppressions.xml
pom.xml

addressing o. a. log4j vulnerability

fix: dependency updates

---

CODEOWNERS

instead of enumeration of single accounts

feat: update CODEOWNERS with group

---

src/main/resources/application-h2.yml
src/main/resources/application-mysql.yml
src/main/resources/application.yml

Remove explicit SQL Dialect definition

Fix: SQL-Dialect
